### ISSUE TITLE
Add docs for missing Commerce.js methods

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/commerce.js#125]
We have a bunch of more reader-friendly docs in this repo (https://github.com/chec/commerce.js/tree/master/docs) that are automatically built into https://commercejs.com/docs. They're missing a few of handy endpoints available with `commerce.checkout` - for instance `commerce.checkout.checkVariant`.

**Comment by jaepass** [comment]
Added in https://github.com/chec/commerce.js/pull/147

**Comment by jaepass** [comment]
Follow up discussion with @eufandem around docs enhancements - 

I think once all the missing methods are added we may or may not want to remove the 'Full SDK ref' doc, now I remember why this page exists because not all methods were included in the main SDK methods ie. `categories.retrieve()` or `cart.refresh()`. Might still be good to keep 'Full SDK ref' as don't need to add the uncommonly used ones and only the more powerful methods that are missing?

**Comment by jaepass** [comment]
Closed by https://github.com/chec/commerce.js/pull/155

**Comment by jaepass** [comment]
cc @eufandem Removed the Full SDK ref page, did a bunch of docs clean up and also added merchants as that was included anyway. Now all endpoints and methods are in the SDK!

**Comment by eufandem** [comment]
Boom, nice work!
