### ISSUE TITLE
Managed inventory not working

### ISSUE THREAD

**Issue by snorresovold** [chec/commerce.js#174]
When you have your inventory as managed people can still buy as much as they want, the value just becomes negative

**Comment by robbieaverill** [comment]
Hi @snorresovold, are you using a sandbox or a live API key?

**Comment by snorresovold** [comment]
Sandbox

**Comment by robbieaverill** [comment]
HI @snorresovold, thanks for reporting this issue. I've had a look into this, and it looks like this happens when you capture a checkout token where you've previously set the quantity for your line items at the cart level. I'll be patching this so it's validated again at the "capture checkout" level, regardless of whether you specify your line items or not in that API call. I'll also patch to ensure it doesn't go below zero.

**Comment by snorresovold** [comment]
Ok, thanks. If I find any other problems I'll let you know

**Comment by robbieaverill** [comment]
Thanks. The fix for this will be released next Wednesday 16th June.

**Comment by snorresovold** [comment]
Is there a similar problem with non-sandbox API-keys?
